apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: kedalab-trigger-auth
  namespace: solace
  labels:
    app: kedalab-trigger-auth
spec:
  secretTargetRef:
    - parameter:   username
      name:        kedalab-solace-secret
      key:         SEMP_USER
    - parameter:   password
      name:        kedalab-solace-secret
      key:         SEMP_PASSWORD
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name:      pqdemo-scaled-object
  namespace: solace
  labels:
    app: pqdemo-scaled-object
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          solace-pqdemo-subscriber
  pollingInterval:  5
  cooldownPeriod:   30
  minReplicaCount:  1
  maxReplicaCount:  12
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          selectPolicy:    Min
          stabilizationWindowSeconds: 45
          policies:
          - type:          Pods
            value:         2
            periodSeconds: 20
        scaleUp:
          selectPolicy:    Max
          stabilizationWindowSeconds: 0
          policies:
          - type:          Pods
            value:         3
            periodSeconds: 10
          # - type:          Percent
          #   value:         100
          #   periodSeconds: 30
  triggers:
  - type: solace-event-queue
    metadata:
      solaceSempBaseURL:       http://kedalab-pubsubplus-dev.solace.svc.cluster.local:8080
      messageVpn:               default
      queueName:                pq12
      messageCountTarget:       '500'
      messageReceiveRateTarget: '90'
#      messageSpoolUsageTarget:  '1000'
    authenticationRef:
      name: kedalab-trigger-auth