apiVersion: v1
kind: Secret
metadata:
  name: solace-pqdemo-secrets
  namespace: pq-demo
  labels:
    app: pqdemo-secrets
type: Opaque
stringData:
  consumer.properties: |
    host=kedalab-pubsubplus-dev.solace.svc.cluster.local:55554
    vpn_name=default
    username=consumer_user
    password=consumer_pwd
    queue.name=pq12
